name: Deploy Auth Microservice
on:
  workflow_run:
    workflows: ["CI Auth Service"]
    types:
      - completed
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/auth-microservice:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get SHA from workflow run
        run: echo "SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Tag as latest and push
        run: |
          docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/auth-microservice:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-microservice:latest
